name: Try build

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build cross platform
        uses: neodyland/rust-ci@7571554b67a8659b848d97fddc07a98db67eecb4
        with:
          package: testbin,testbin2
          install-rustup: false
          install-openssl: true
          cache: true
      - name: Get list
        run: ls .out/aarch64
