name: Try build

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build cross platform
        uses: neodyland/rust-ci@b60810bf70d1451fe3852b3b5e6684a4be7a9e08
        with:
          package: testbin,testbin2
          install-rustup: false
          install-openssl: true
          cache: true
      - name: Get list
        run: ls .out/aarch64
