name: Try cross platform build

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup rust
        uses: actions-rs/toolchain@v1
      - name: Build cross platform
        uses: neodyland/rust-ci@133428940f08a0879709f02e6805c1bf7ce62de6
        with:
          package: testbin,testbin2
      - name: List result x86-64
        run: ls .out/x86-64
      - name: List result aarch64
        run: ls .out/aarch64